spring.application.name=corporate-library-api

spring.datasource.url=jdbc:postgresql://localhost:5433/corporate_library_db

spring.datasource.username=SKDEV9
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=validate
api.security.token.secret=minha_senha_super_secreta_123