# ----------------------------------------
# CONFIGURACOES DO BANCO DE DADOS
# ----------------------------------------

spring.application.name=corporate-library-api
spring.datasource.url=jdbc:postgresql://localhost:5433/corporate_library_db

spring.datasource.username=SKDEV9
spring.datasource.password=123456
api.security.token.secret=minha_senha_super_secreta_123

# ----------------------------------------
# CONFIGURACOES DO HIBERNATE / JPA
# ----------------------------------------
# Como vocE usou o Flyway (segundo o seu print do Gupy), deixe o ddl-auto como validate ou none
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true