# ----------------------------------------
# CONFIGURACOES DO BANCO DE DADOS
# ----------------------------------------

spring.application.name=corporate-library-api
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}

# ----------------------------------------
# CONFIGURACOES DO HIBERNATE / JPA
# ----------------------------------------
# Como vocE usou o Flyway (segundo o seu print do Gupy), deixe o ddl-auto como validate ou none
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true