create table book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    title varchar(100) not null,
    author varchar(50) not null,
    isbn varchar(20) not null,
    is_available boolean default true
);