create table users (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    nome varchar(50) not null,
    matricula varchar(50) unique,
    email varchar(100) unique not null,
    senha varchar(255) not null,
    data_cadastro TIMESTAMP default CURRENT_TIMESTAMP

);