CREATE TABLE loans (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    user_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    data_emprestimo DATE NOT NULL,
    data_devolucao DATE NOT NULL,
    devolvido BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_loans_user_id FOREIGN KEY (user_id) references users(id),
    CONSTRAINT fk_book_user_id FOREIGN KEY (book_id) references book(id)

)